# SerpApi Search
SERPAPI_API_KEY: YOUR_SERPAPI_API_KEY
SERPAPI_ENGINE: # SerpApi engine to use, defaults to "google". Can be "bing", "yahoo", "baidu", "duckduckgo", "yandex", "naver", ...
SERPAPI_NO_CACHE: # Set to "true" if you want to force SerpApi to fetch the results even if a cached version is already present